export default class Outlet {
  constructor(
    public id: number,
    public name: string,
    public type: number,
    public typeText: string,
    public address: string,
    public contact: string,
    public openHour: string,
    public closeHour: string,
    public image: string | null,
    public mapUrl: string | null,
    public isReservable: boolean,
    public openForReservation: boolean,
    public openStatus: boolean,
    public openStatustext: string,
    public isUsingGuestLayout: boolean,
    public cutOffDate: string,
    public maximumEta: string | null,
    public reservationPaymentType: number,
    public reservationPaymentTypetext: string,
    public useTax: boolean,
    public useService: boolean,
    public tax: number,
    public service: number,
    public can_refund: boolean,
    public maxStandingCapacity: number,
    public isActive: boolean,
    public isUsingTicket: boolean,
    public timezone: string,
    public ticketTableMapImage: string | null
  ) {}

  public static fromJson(json: any): Outlet {
    return new Outlet(
      json.id,
      json.name,
      json.type,
      json.type_text,
      json.address,
      json.contact,
      json.open_hour,
      json.close_hour,
      json.image,
      json.map_url,
      json.is_reservable,
      json.open_for_reservation,
      json.open_status,
      json.open_status_text,
      json.is_using_guest_layout,
      json.cut_off_date,
      json.maximum_eta,
      json.reservation_payment_type,
      json.reservation_payment_type_text,
      json.use_tax,
      json.use_service,
      json.tax,
      json.service,
      json.can_refund,
      json.max_standing_capacity,
      json.is_active,
      json.is_using_ticket,
      json.timezone,
      json.ticket_table_map_image
    );
  }
}
